In [4]:
#!pip install names
import names
import numpy as np
import pandas as pd

In [18]:
num_applicants = 300

# uses numpy.random.choice to weight each category
# _categories and _probability can be modified and extended, but each array must be of equal length
# contains missing values, because we expect those in source data

gender_categories = ['male','female','other','']
# gender_probability = [.48,.48,.03,.01]
gender_probability = [.75,.20,.03,.02]

career_categories = ['student','junior-faculty','senior-faculty','']
# career_probability = [.33,.33,.33,.01]
career_probability = [.10,.60,.29,.01]

country_categories = ['OECD','non-OECD',''] # see http://www.oecd.org/about/membersandpartners/
# country_probability = [.49,.49,.02]
country_probability = [.90,.08,.02]

subfield_categories = ['solar','cosmology','astrophysics','exoplanets','']
# subfield_probability = [.24,.24,.24,.24,.04]
subfield_probability = [.05,.60,.15,.15,.05]

first_time_categories = ['first_time','returning','']
# first_time_probability = [.49,.49,.02]
first_time_probability = [.33,.66,.01]

age_categories = ['age']
age_mean = 32
age_omission = 0.25

In [19]:
gender_array = np.random.choice(gender_categories, p=gender_probability, size=num_applicants, replace=True)

name_array = [names.get_full_name(gender=i) for i in gender_array]

career_stage_array = np.random.choice(career_categories, p=career_probability,size=num_applicants,replace=True)

country_array = np.random.choice(country_categories, p=country_probability,size=num_applicants,replace=True)

subfield_array = np.random.choice(subfield_categories, p=subfield_probability,size=num_applicants,replace=True)

first_time_array = np.random.choice(first_time_categories,p=first_time_probability,size=num_applicants,replace=True)

age_array = np.random.poisson(lam=age_mean, size=num_applicants).astype(np.float)
age_array[np.random.choice(np.arange(num_applicants, dtype=int), replace=False, size=int(age_omission * num_applicants))] = np.nan

In [20]:
df2 = pd.DataFrame({
        'applicant_name':name_array,
        'gender':gender_array,
        'career_stage':career_stage_array,
        'country':country_array,
        'subfield':subfield_array,
        'first_time':first_time_array,
        'age':age_array
        })

df2

,age,applicant_name,career_stage,country,first_time,gender,subfield
0,25.0,Lamar Foster,junior-faculty,OECD,returning,male,cosmology
1,33.0,Betty Jones,junior-faculty,OECD,returning,female,solar
2,41.0,Mark Garvin,junior-faculty,OECD,returning,male,cosmology
3,NaN,Margaret Lee,senior-faculty,non-OECD,returning,female,cosmology
4,NaN,Nicholas Marrara,junior-faculty,OECD,first_time,male,cosmology
5,25.0,Luis Perez,junior-faculty,OECD,returning,male,cosmology
6,NaN,Christine Bell,student,OECD,returning,female,cosmology
7,29.0,Betty Colon,junior-faculty,OECD,returning,female,
8,36.0,Charles Cannon,senior-faculty,OECD,returning,male,cosmology
9,NaN,Emily Harbin,junior-faculty,OECD,returning,female,astrophysics
10,29.0,Patricia Mcgraw,junior-faculty,OECD,returning,female,cosmology
11,31.0,Janice Claxton,junior-faculty,OECD,returning,female,exoplanets
12,33.0,Jeffrey Carrell,junior-faculty,non-OECD,first_time,male,cosmology
13,28.0,Regina David,junior-faculty,OECD,returning,female,cosmology
14,43.0,Donnie Patterson,senior-faculty,OECD,returning,male,cosmology
15,34.0,Joseph Kondracki,senior-faculty,OECD,returning,male,cosmology
16,NaN,Mark Brennen,senior-faculty,OECD,first_time,male,astrophysics
17,34.0,Nanci Mclaughlin,student,OECD,first_time,female,cosmology
18,26.0,Shirley Cooper,student,OECD,first_time,male,astrophysics
19,NaN,Dusty Palomo,student,OECD,first_time,male,cosmology
20,33.0,John Monat,junior-faculty,OECD,first_time,male,cosmology
21,NaN,Larry Harris,junior-faculty,OECD,returning,male,cosmology
22,NaN,Steven Hulse,student,OECD,first_time,male,cosmology
23,27.0,Stephen Johnson,student,OECD,returning,male,cosmology
24,NaN,Daniel Mitchell,junior-faculty,OECD,returning,male,exoplanets
25,31.0,Russel Thompson,junior-faculty,OECD,returning,male,cosmology
26,33.0,Stuart Schlindwein,senior-faculty,OECD,returning,male,cosmology
27,NaN,Thomas Oviedo,junior-faculty,OECD,returning,male,cosmology
28,23.0,Michael Hilsinger,senior-faculty,OECD,first_time,male,cosmology
29,25.0,Phyllis Park,senior-faculty,OECD,first_time,female,astrophysics
...,...,...,...,...,...,...,...
270,34.0,Agnes Gaines,senior-faculty,OECD,returning,female,astrophysics
271,27.0,Justin Lane,junior-faculty,OECD,returning,male,exoplanets
272,41.0,Jung Smith,senior-faculty,OECD,first_time,female,
273,31.0,Eddie Dawkins,junior-faculty,OECD,first_time,male,cosmology
274,32.0,Joel Perkins,junior-faculty,OECD,returning,male,cosmology
275,31.0,Paula Mitchell,junior-faculty,OECD,first_time,female,exoplanets
276,39.0,Lorraine Raspberry,junior-faculty,OECD,returning,female,exoplanets
277,NaN,Evelyn Rainbolt,student,OECD,first_time,female,cosmology
278,38.0,Stephen Carter,senior-faculty,OECD,returning,male,cosmology
279,41.0,Christopher Kim,junior-faculty,OECD,returning,other,cosmology
280,43.0,Laurence Delfin,senior-faculty,OECD,first_time,male,
281,30.0,Craig Adams,junior-faculty,OECD,returning,male,astrophysics
282,42.0,Alice Conley,junior-faculty,OECD,returning,female,astrophysics
283,28.0,John Hobbs,senior-faculty,OECD,first_time,male,cosmology
284,36.0,James Cacciatori,senior-faculty,OECD,first_time,male,solar
285,29.0,James Maryland,senior-faculty,OECD,returning,male,cosmology
286,35.0,Herbert Deininger,senior-faculty,OECD,first_time,male,cosmology
287,28.0,Carl Goldie,junior-faculty,OECD,returning,male,cosmology
288,28.0,Robert Ward,junior-faculty,OECD,first_time,male,cosmology
289,20.0,Lea Winget,senior-faculty,OECD,returning,other,cosmology
290,36.0,James Maxwell,junior-faculty,OECD,returning,male,cosmology
291,32.0,Barbara Saddler,student,OECD,returning,,cosmology
292,38.0,Eduardo Turner,senior-faculty,OECD,first_time,male,cosmology
293,35.0,Juan Bragg,senior-faculty,OECD,first_time,male,exoplanets
294,31.0,Matthew Wilson,junior-faculty,OECD,returning,male,
295,35.0,Raymond Kinneman,junior-faculty,OECD,returning,male,exoplanets
296,NaN,Joseph Witt,senior-faculty,OECD,returning,male,cosmology
297,27.0,William Talley,junior-faculty,OECD,first_time,male,cosmology
298,25.0,Shawnda Hall,junior-faculty,OECD,returning,female,exoplanets
299,NaN,Rafael Fair,junior-faculty,OECD,returning,male,exoplanets

In [22]:
fname = 'test-data.csv'
df2.to_csv(fname,index=False)